<?php

namespace Tracker\Bundle\BackBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * SeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends EntityRepository
{
    public function searchForTrackedSeries($title)
    {
        $series = $this->findAll();
        $normalizedTitle = $this->normalize($title);

        foreach ($series as $show) {
            if (preg_match('/^' . $show->getNormalizedName() . '[a-zA-Z0-9]*?/', $normalizedTitle)) {
                return $show;
            }
        }

        throw new \Exception('Nie znaleziono serialu dla ' . $title);
    }

    public function normalize($string)
    {
        $string = preg_replace('/\s/', '', $string);
        $string = preg_replace('/[^a-zA-Z0-9]/', '', $string);
        $string = mb_strtolower($string);

        return $string;
    }
}
