<?php

namespace Tracker\Bundle\BackBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;

use Tracker\Bundle\BackBundle\Entity\Series;

/**
 * TorrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorrentRepository extends EntityRepository
{
    public function getLatestQuery()
    {
        return $this->_em
            ->createQuery('SELECT t FROM Tracker\Bundle\BackBundle\Entity\Torrent t ORDER BY t.date DESC');
    }

    public function getLatest($limit = 10)
    {
        return $this->getLatestQuery()->setMaxResults($limit)->getResult();
    }

    public function findBySeries(Series $series)
    {
        $query = $this->_em
            ->createQuery('SELECT
                                t
                           FROM
                                Tracker\Bundle\BackBundle\Entity\Torrent t
                           JOIN
                                t.episode e
                           JOIN
                                e.series s
                           WHERE
                                s.id = :series');

        $query->setParameter('series', $series);
        return $query->getResult();
    }
}
