parameters:
#    tracker_user.example.class: Tracker\Bundle\UserBundle\Example

services:
#    tracker_user.example:
#        class: %tracker_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
